site_name: My Documentation
site_url: https://renefallentin.github.io/grp3/

nav:
  - Home: index.md
  - Getting Started: getting-started.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences