site_name: H1 Serverprojekt
site_url: https://renefallentin.github.io/grp3/

nav:
  - Home: index.md
  - Basic Configuration: basicconfig.md
  - Network:
    - Topology: network/topology.md
    - Routers:
      - R1-DK1: network/routers/dk1-r1.md
      - R1-DK2: network/routers/dk2-r1.md
    - Switches:
      - SW-L3-DK1: network/switches/dk1-sw-l3.md
      - SW-L2-DK1: network/switches/dk1-sw-l2.md
      - SW-L3-DK2: network/switches/dk2-sw-l3.md
      - SW-L2-DK2: network/switches/dk2-sw-l2.md
    - Servers:
      - SRV-01-DK1: network/servers/dk1-srv-01.md
      - SRV-02-DK1: network/servers/dk1-srv-02.md
      - SRV-03-DK1: network/servers/dk1-srv-03.md
      - SRV-04-DK1: network/servers/dk1-srv-04.md
      - SRV-05-DK2: network/servers/dk2-srv-05.md
    - Clients:
      - Client 1: network/clients/client-1.md
      - Client 2: network/clients/client-2.md
  - Active Directory: ad.md

theme:
  name: material
  font: 
     text: merriweather sans-serif
     code: red hat mono

  icon:
    logo: fontawesome/solid/3

  palette:
    - scheme: slate
      primary: yellow
      accent: yellow

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

plugins:
  - d2:
      layout: elk
      theme: 200
      pad: 0

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/topology-zoom.js
  - js/topology-redundancy.js

extra:
  generator: false