site_name: H1 Serverprojekt
site_url: https://renefallentin.github.io/grp3/

nav:
  - Home: index.md
  - Basic Configuration: basicconfig.md
  - Network:
    - Topology: network/topology.md
    - Routers:
      - DK1-R1: network/routers/dk1-r1.md
      - DK2-R1: network/routers/dk2-r1.md

    - Switches:
      - DK1-SW-L3: network/switches/dk1-sw-l3.md
      - DK1-SW-L2: network/switches/dk1-sw-l2.md
      - DK2-SW-L3: network/switches/dk2-sw-l3.md
      - DK2-SW-L2: network/switches/dk2-sw-l2.md

    - Servers:
      - DK1-SRV-01: network/servers/dk1-srv-01.md
      - DK1-SRV-02: network/servers/dk1-srv-02.md
      - DK1-SRV-03: network/servers/dk1-srv-03.md
      - DK1-SRV-04: network/servers/dk1-srv-04.md
      - DK2-SRV-05: network/servers/dk2-srv-05.md

    - Clients:
      - Client 1: network/clients/client-1.md
      - Client 2: network/clients/client-2.md

theme:
  name: material
  font: 
     text: merriweather sans-serif
     code: red hat mono

  icon:
    logo: fontawesome/solid/3

  palette:
    - scheme: slate
      primary: lime
      accent: deep-purple

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

plugins:
  - d2:
      layout: elk
      theme: 200
      pad: 0

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css